version: '3'
services:
  mysqldb:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kaddemdb
    volumes:
      - db:/var/lib/mysql      
  backend:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    ports:
      - "8090:8089"  # Use quotes for port mappings
    stdin_open: true
    tty: true
    volumes:
      - .m2:/root/.m2    
volumes:
  db:
