# docker-compose.yml
version: '2'
services:
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
   mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kaddemdb
    ports:
      - "3307:3306"     
    volumes:
      - db:/var/lib/mysql
  backend:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    ports:
      - "8090:8089"
    stdin_open: true
    tty: true
    volumes:
      - .m2:/root/.m2    
volumes:
  db:
