version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ""  # Enclose the password in quotes
      MYSQL_DATABASE: "kaddemdb"
    volumes:
      - db:/var/lib/mysql

  backend:
    depends_on:
      - mysqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/kaddem
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      
    image: jesssser/kaddem-0.0.1.jar
    restart: on-failure
    ports:
      - "8082:8082"  # Use quotes for port mappings
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
  .m2:
