version: '3'
services:
  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kaddemdb
    volumes:
      - db:/var/lib/mysql        
volumes:
  db:
