version: "3.8"

services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "kaddemdb"
    volumes:
      - db:/var/lib/mysql

  backend:
    depends_on:
      - mysql
    extra_hosts:
      - "mysql:mysql"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/kaddem
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      
    build: ./
    restart: on-failure
    ports:
      - "8089:8089"  # Use quotes for port mappings
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
  .m2:
