version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=0000
      - MYSQL_DATABASE=kaddemdb
    volumes:
      - db:/var/lib/mysql
  spring-app:
    image: rafik101/kaddem-6.6.6.jar
    depends_on:
      - mysql
    ports:
      - 8089:8089
    stdin_open: true
    tty: true
    volumes:
      - .m2:/root/.m2    
volumes:
  db:
