version: '3'
services:
  db:
    container_name: mysql
    image: mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_DATABASE=khaddemapp
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
      - $PWD/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  spring_app:
    container_name: kaddem
    image: mouhibbengayes-5sae3
    restart: on-failure
    build: .
    ports:
      - 8089:8089

    depends_on:
      - db
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/khaddemapp?useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=
volumes:
  mysql:
    driver: local
