# docker-compose.yml
version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=0000
      - MYSQL_DATABASE=kaddemdb
    volumes:
      - db:/var/lib/mysql
  back-rest:
    image: houssem13/kaddem-0.0.1.jar
    depends_on:
      - mysql
    ports:
      - 8089:8089
    stdin_open: true
    tty: true
    volumes:
      - .m2:/root/.m2    
volumes:
  db:
