version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD:# Set your desired root password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Allow empty root password
    volumes:
      - db:/var/lib/mysql

  backend:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    ports:
      - 6868:8082
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
  .m2:
