version: '3'
services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kaddemdb
  backend:
    depends_on:
      - mysqldb
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306
    build: ./
    restart: on-failure
    ports:
      - "8089:8089"  # Use quotes for port mappings
    stdin_open: true
    tty: true
