version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3307:3306"   
    environment:
      MYSQL_DATABASE: "kaddemdb"
      MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
